### PR TITLE
Use Bootstrap to be responsive.

### PR DESCRIPTION
**Pull request by computerfr33k**
Let me know if you guys want to use bootstrap. As the current site is not responsive as I've noticed the forms don't look quite right when I split my browser on my screen with the IDE split as well. (side by side)

### CODE REVIEW

**Comment by brookemcentee** [comment]
We talked about using Bootstrap week 1, but Charlie said that we
shouldn't...I forget his reasoning but he can chime in if he wants to.

**Comment by idontusenumbers** [comment]
I think boot strap adds more work than it takes away. If you guys want to use it, that's fine.

**Comment by idontusenumbers** [comment]
Can we wait to add bootstrap/responsive until the app is fully functional and meets all the requirements?

**Comment by computerfr33k** [comment]
I feel that if you use bootstrap from the start it is much easier down the road because otherwise then you have to go and rework everything to then work with bootstrap. Plus, how does bootstrap add more work? It's pretty easy to use and you get a lot of stuff for free such as responsive grids and styling, and etc. But, then again I'm not really the one doing the front-end so I guess it's up to them to decide what they want to do. Those are just my thoughts.

**Comment by idontusenumbers** [comment]
If the decision is to use bootstrap, I agree, definitely easy from the start. I've worked and spoke with a lot of people that decided after starting with bootstrap to abandon it, and in that case, its similarly hard to rewrite everything. I wouldn't say those things are free; you need to learn bootstrap and worth within it's confines. It's an extra dependency too.

**Comment by brookemcentee** [comment]
I know bootstrap well, the only issue is I would have to rewrite a lot of
frontend code...and I don't really want to haha. I don't think
responsiveness is necessary for the scope of our project...I'd rather just
get it done :)

**Comment by nkar94** [comment]
I agree with Brooke and Charlie. Not trying to add more work to all the work I already have lol.

**Pull request closed without merging**
